apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import UserLoginForm, PassResetForm, PassResetConfirmForm

app_name="account_"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    #path ('', connection.new_user, name = 'new_user'),
    path('check-registration/', views.registration_check, name="registration_check"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('delete/', views.delete_account, name="delete_account"),
    path('delete_confirmation/', auth_views.TemplateView.as_view(
        template_name='account/user/delete_confirmation.html'), name="delete_confirmation"),

    #this here takes u to form where u enter email, then on click of button, to page saying u did it successfully
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='account/user/password_reset_form.html',
        success_url='password_reset_email_confirm',
        email_template_name='account/user/password_reset_email.html',
        form_class=PassResetForm),
        name="password_reset"),

    path('edit_login/', auth_views.PasswordResetView.as_view(
            template_name='account/user/password_reset_form.html',
            success_url='password_reset_email_confirm',
            email_template_name='account/user/password_reset_email.html',
            form_class=PassResetForm),
            name="edit_login"),

    #d page saying u did it successfully
    path('password_reset/password_reset_email_confirm/', auth_views.TemplateView.as_view(
        template_name='account/user/reset_status.html'), name="password_reset_done"),

    #this appears in ur email, on click this takes u to password_reset_complete
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/user/password_reset_confirm.html',
        success_url='/account/password_reset_complete/',
        form_class=PassResetConfirmForm),
        name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.TemplateView.as_view(
        template_name='account/user/reset_status.html'), name="password_reset_complete"),
    path('register/', views.account_registration, name="register"),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activation,  name="activate_"),
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name="logout"),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/set_default/", views.set_default, name="set_default"),
    #path("user_orders/", views.user_orders, name="user_orders"),
    path("", views.search_account, name="search_account"),
    path('dashboard_ajax/', views.dashboard_ajax, name="dashboard_ajax"),
    path("likes_and_wishlist/", views.likes_and_wishlist, name="likes_and_wishlist"),
    path("wishlist/wishlist_add_and_remove/<int:id>/", views.wishlist_add_and_remove, name="wishlist_add_and_remove"),
    path("wishlist/remove_from_wishlist/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("likes/remove_from_likes/", views.remove_from_likes, name="remove_from_likes"),
]

apps/payment/urls.py
from django.urls import path
from . import views

app_name="payment_"
urlpatterns = [
    path('', views.payment, name="payment"),
    path('initiate_payment/', views.initiate_payment, name="initiate_payment"),
    path('<str:ref>/', views.verify_payment, name="verify_payment"),
    path('orderplaced/', views.order_placed, name="order_placed"),
    #path("paystack", include(('paystack.urls', 'paystack'),namespace='paystack'))
    #path('webhook/', views.stripe_webhook, name="webhook"),
]

mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('apps.payment.urls', namespace='payment_')),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.core.urls', namespace='core_')),
    path('', include('apps.product.urls', namespace='product_')),
    path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/payment/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
#from .paystack import PayStack
import secrets


class Payment(models.Model):
    email = models.CharField(_('email address'),max_length=150, unique=True)
    amount = models.PositiveIntegerField()
    ref = models.CharField(max_length=20, blank=True)
    verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('date_created',)

    def __str__(self):
        return f"Payment: {self.amount}"

    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref=ref
        super().save(*args, **kwargs)

    def amount_value(self) -> int:
        return self.amount * 100

    def verify_payment(self):
        pass
        """paystack = PayStack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            if result['amount'] / 100 == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False"""

apps/payment/forms.py
from django import forms
from .models import Payment


class PaymentForm(forms.ModelForm):
    class Meta:
        model= Payment
        fields=("amount", "email",)

apps/payment/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from decimal  import Decimal
from django.http import HttpResponse
from django.http.request import HttpRequest

from apps.cart.cart import Cart
from apps.cart.forms import CheckoutForm
from apps.order.utilities import checkout, email_notify_vendor, email_notify_customer, payment_confirmation
from apps.vendor.models import Vendor
from apps.product.models import Product
#import stripe

from .forms import PaymentForm
from .models import Payment

@login_required
def CartView(request):
    #(id__in=id, category__slug=slug)
    newest_products = Product.objects.filter(is_active=True, in_stock=True).order_by('-date_added')[:3]
    #newest_products = Product.product_manager.all().order_by('-date_added')[:3]
    return render(request, 'payment/payment.html', {'newest_products': newest_products})

@login_required
def checkout_view(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        """if form.is_valid():
            stripe.api_key = settings.STRIPE_SECRET_KEY

            stripe_token = form.cleaned_data['stripe_token']

            try:
                charge = stripe.Charge.create(
                    amount=int(account.get_total_cost() * 100),
                    currency='USD',
                    description='Charge from eCommerce',
                    source=stripe_token
                )
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                phone = form.cleaned_data['phone']
                address = form.cleaned_data['address']
                zipcode = form.cleaned_data['zipcode']
                place = form.cleaned_data['place']

                orderReciept = checkout(request, first_name, last_name, email, address, zipcode, place, phone, account.get_total_cost())
                account.clear()

                email_notify_vendor(orderReciept)
                email_notify_customer(orderReciept)

                return redirect('cart_:success_')

            except Exception:
                messages.error(request, 'There was something wrong with the payment')"""
    else:
        form = CheckoutForm()
    return render(request, 'payment/payment.html')  #, {'form': form})  # , 'stripe_pub_key':settings.STRIPE_PUB_KEY})


@login_required
def payment(request):
    cart = Cart(request)
    """
    try:
        total = str(chats.get_total_price())
        total = total.replace('.','')
        #total = int(total)
        stripe.api_key = settings.STRIPE_SECRET_KEY
    
        intent = stripe.PaymentIntent.create(
            amount=total,
            currency='gpb',
            metadata={'userid': request.user.id}
        )
        return render(request, 'payment/payment.html', {'client_secret': intent.client_secret})
    
    except Exception:
        #messages.error(request, 'There was something wrong with the payment')
    """

"""
#
@csrf_exempt
def stripe_webhook(request):
    payload=request.body
    event=None
    try:
        event=stripe.Event.construct_from(
            json.loads(payload), stripe.api_key
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)
    if event.type== 'payment_intent_succeeded':
        payment_confirmation(event.data.object.client_secret)
    else:
        print('unhandled event type {}'.format(event.type))
    return HttpResponse(status=200)"""

def order_placed(request):
    cart = Cart(request)
    cart.clear()
    return render(request, 'payment/orderplaced.html')

@login_required
def initiate_payment(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment =payment_form.save()
            return render(request, 'payment/make_payment.html', {'payment':payment,
                                                                 'paystack_public_key':settings.PAYSTACK_PUBLIC_KEY})
    else:
        payment_form=PaymentForm()
    return render(request, 'payment/initiate_payment.html', {'payment': payment_form})

def verify_payment(request: HttpRequest, ref:str) -> HttpResponse:
    payment = get_object_or_404(Payment, ref=ref)
    verified = payment.verify_payment()
    if verified:
        messages.success(request, "Veriication Successful")
    if verified:
        messages.error(request, "Veriication Failed")
    return redirect('payment_:initiate_payment')



"""
PAYSTACK_SECRET_KEY=os.environ.get(PAYSTACK_SECRET_KEY)
CRISPY_TEMPLATE_PACK="bootstrap4"
"""

apps/payment/templates/payment/initiate_payment.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="col-md-12">
                <div class="login d-flex align-items-center py-5">
                   <div class="container">
                        <div class="row">
                            <div id="payment-forms" class="col-12 col-lg-6 mx-auto">
                                <h3 class="subtitle">Payment</h3>
                                <div id="card-errors" class="a" role="alert"></div>
                                <form method="post" action="." id="payment-form">
                                    {% csrf_token %}
                                    {% if form.errors %}
                                        <div class="notification is-danger">
                                            <ul>
                                            {% for field in form %}
                                                {% for error in field.errors %}
                                                    <li><strong>{{ field.label }}</strong>{{ error }}</li>
                                                {% endfor %}
                                            {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                    {{ payment_form | crispy}}
                                    <input type="submit" value="submit">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function payWithPayStack(){
        let currency = "NGN";
        let plan = "";
        let ref = "{{payment.ref}}"
        let obj = {
            key: "{{paystack_public_key}}",
            email: "{{payment.email}}",
            amount: "{{payment.amount_value}}",
            ref:ref,
            callback: function(response){
                window.location.href = {% url 'verify-payment' payment.ref %}
            }
        }
        if (Boolean(currency)){
            obj.currency = currency.toUpperCase()
        }
        if (Boolean(plan)){
            obj.plan = plan;
        }
        var handler = PaystackPop.setup(obj);
    }
</script>

{% endblock %}

apps/payment/templates/payment/make_payment.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="col-md-12">
                <div class="login d-flex align-items-center py-5">
                   <div class="container">
                        <div class="row">
                            <div id="payment-forms" class="col-12 col-lg-6 mx-auto">
                                <h3 class="subtitle">Payment</h3>
                                <script src="https://js.paystack.co/v1/inline.js"></script>
                                <button id="django-paystack-button" onclick="payWithPayStack()">Make Payment</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function payWithPayStack(){
        let currency = "NGN";
        let plan = "";
        let ref = "{{payment.ref}}"
        let obj = {
            key: "{{paystack_public_key}}",
            email: "{{payment.email}}",
            amount: "{{payment.amount_value}}",
            ref:ref,
            callback: function(response){
                window.location.href = {% url 'payment:verify_payment' payment.ref %}
            }
        }
        if (Boolean(currency)){
            obj.currency = currency.toUpperCase()
        }
        if (Boolean(plan)){
            obj.plan = plan;
        }
        var handler = PaystackPop.setup(obj);
    }
</script>
{% endblock %}

apps/payment/templates/payment/orderplaced.html
 <div>
    <h3>Order has been placed</h3>
    <p>check your email for confirmation</p>
    <a href="{% url 'account_:dashboard' %}">See order</a>
</div>
 <!-- <form>
     <script src="https://js.paystack.co/v1/inline.js"></script>
     <button type="button" onclick="makePayment()"></button>
 </form>
 <script>
     function makePayment(){
        var handler = PaystackPop.setup({
            key = 'hh75-]]]]'
            email: {{ email }},
            amount: 600,
            currency: 'NGN',
            ref: ""+Math.floor((Math.random() * 100000000) + 1),
            ref: ' '+Math.floor((Math.random() * 1000000000) + 1),
            callback: function(response){
                alert('success, transaction ref is' + response.reference);
            },
            onClose: function(){
                alert('success');
            }
        });
        handler.openIframe();
     }
 </script>
 -->

apps/payment/templates/payment/payment.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Checkout{% endblock %}

<style>
    .account-form input{
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }
    .form-control input{
        border: 2px solid #ccc;
    }
    .account-form input:focus{
        border-color: #1497ff;
        box-shadow: inset 0 0 0 rgba(0,0,0,0.075),  0 0 0 rgba(255,0,0,0.6);
    }
</style>
{% block content %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="col-md-12">
                <div class="login d-flex align-items-center py-5">
                   <div class="container">
                        <div class="row">
                            <div id="payment-forms" class="col-12 col-lg-6 mx-auto">
                                <h3 class="subtitle">Contact information</h3>
                                <div id="card-errors" class="a" role="alert"></div>
                                <form method="post" action="." id="payment-form">
                                    {% csrf_token %}
                                    {% if form.non_field_errors %}
                                        <div class="control">
                                            {{ form.non_field_errors }}
                                        </div>
                                    {% endif %}
                                    {% if form.errors %}
                                        <div class="notification is-danger">
                                            <ul>
                                            {% for field in form %}
                                                {% for error in field.errors %}
                                                    <li><strong>{{ field.label }}</strong>{{ error }}</li>
                                                {% endfor %}
                                            {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                    <div class="row g-3">
                                        <div class="col-sm-7">
                                            <label for="firstname" class="form-label">First name</label>
                                            <input type="text" class="form-control" id="custName" placeholder="" name="first_name">
                                            <div class="invalid-feedback">Valid first name is required.</div>
                                        </div>
                                        <div class="col-sm-7">
                                            <label for="email" class="form-label">Email<span class="text-muted">(Optional)</span></label>
                                            <input type="email" class="form-control" id="email" placeholder="you@example.com" name="first_name">
                                            <div class="invalid-feedback">please enter a valid email address for shipping updates.</div>
                                        </div>
                                        <div class="col-12">
                                            <label for="address" class="form-label">Address</label>
                                            <input type="text" class="form-control" id="custAdd" placeholder="" name="first_name">
                                            <div class="invalid-feedback">Valid first name is required.</div>
                                        </div>
                                        <div class="col-12">
                                            <label for="address2" class="form-label">Address2<span class="text-muted">(Optional)</span></label>
                                            <input type="text" class="form-control" id="custAdd2" placeholder="" name="first_name">
                                            <div class="invalid-feedback">Valid first name is required.</div>
                                        </div>
                                        <div class="col-md-5">
                                            <label for="country" class="form-label">Country</label>
                                            <select class="form-select" id="country" required>
                                            <option value=""></option>
                                            <option value=""></option>
                                            <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Please select a valid country.</div>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="state" class="form-label">State</label>
                                            <select class="form-select" id="state" required>
                                            <option value=""></option>
                                            <option value=""></option>
                                            <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Please select a valid state.</div>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="postCode" class="form-label">Post Code</label>
                                            <input class="form-select" id="postCode" required>
                                            <div class="invalid-feedback">Please select a valid postCode.</div>
                                        </div>
                                        <div class="col-md-5">
                                            <label for="city" class="form-label">City</label>
                                            <select class="form-select" id="city" required>
                                            <option value=""></option>
                                            <option value=""></option>
                                            <option value=""></option>
                                            </select>
                                            <div class="invalid-feedback">Please select a valid city.</div>
                                        </div>
                                    </div>

                                    <hr>
                                    <h4 class="subtitle">Payment information</h4>
                                    <label for="card-element">Credit or debit card</label>
                                    <div id="card-element">

                                    </div>
                                    <button id="submit" class="buttom is-dark mt-4 is-uppercase" type="text" data-secret="{{ client_secret }}">Pay</button>

                                    {% if messages %}
                                        {% for message in messages %}
                                            <div class="notification is-danger">{{ message }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static ' scripts/payment/main.js' %}" data-rel-js></script>
{% endblock %}





<!-- <form method="post" action="." id="payment-form">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div class="control">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    {% if form.errors %}
        <div class="notification is-danger">
            <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li><strong>{{ field.label }}</strong>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="columns">
        <div class="column is-6">
            <div class="field">
                <label>First name</label>
                <div class="control">
                    <input class="input" type="text" name="first_name">
                </div>
            </div>
            <div class="field">
                <label>Last name</label>
                <div class="control">
                    <input class="input" type="text" name="last_name">
                </div>
            </div>
            <div class="field">
                <label>E-mail</label>
                <div class="control">
                    <input class="input" type="email" name="email">
                </div>
            </div>
            <div class="field">
                <label>Phone</label>
                <div class="control">
                    <input class="input" type="text" name="phone">
                </div>
            </div>
            <div class="field">
                <label>Address</label>
                <div class="control">
                    <input class="input" type="text" name="address">
                </div>
            </div>
            <div class="field">
                <label>Zip code</label>
                <div class="control">
                    <input class="input" type="text" name="zip_code">
                </div>
            </div>
            <div class="field">
                <label>Place</label>
                <div class="control">
                    <input class="input" type="text" name="place">
                </div>
            </div>
        </div>
    </div>

    <h2 class="subtitle">Payment information</h2>
    <div id="card-element"> -->
        <!-- A stripe element will be addedd here-->
    <!-- </div>
    {% if messages %}
        {% for message in messages %}
            <div class="notification is-danger">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="field">
        <div class="control">
            <button class="buttom is-dark mt-4 is-uppercase" type="text" name="place">Checkout</button>
        </div>
    </div>
</form> -->