apps/communication/urls.py
from django.urls import path
from . import views

app_name="message_"
urlpatterns = [
    path("send-fleet-message", views.send_fleet_message, name="send_fleet_message"),
    path("<slug:user_unique_id>/<slug:logged_in_user_unique_id>/", views.get_message, name="chat_platform2"),
    path("<slug:user_or_vendor_unique_id>", views.messages_history, name="messages_history"),
    path('', views.make_comment, name="make_comment"),
]

apps/core/urls.py
from django.urls import path
from . import views
from apps import communication

app_name="core_"
urlpatterns = [
    path('', views.frontpage, name="frontpage"),
    path('contact/', views.contact, name="contact"),
    path('search/<slug:category>/', views.category_search, name="category_search"),
    path("<slug:user_unique_id>/<slug:logged_in_user_unique_id>/error", communication.views.send_message, name="send_msg"),
]

mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('apps.payment.urls', namespace='payment_')),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.core.urls', namespace='core_')),
    path('', include('apps.product.urls', namespace='product_')),
    path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/communication/models.py
from django.db import models
from django.conf import settings

import datetime
import uuid

from apps.vendor.models import Vendor
from apps.account.models import UserBase


class Messages(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    #vendor = models.ForeignKey(Vendor, related_name='vendors_msg', on_delete=models.CASCADE)
    sender_id_unique = models.CharField(null=True, max_length=50)
    reciever_id_unique =  models.CharField(max_length=50)
    content =  models.CharField(max_length=255)
    is_seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        ordering=['-created_at']

    def __str__(self):
        return f'from {self.sender_id_unique} to {self.reciever_id_unique}'

    def get_date(self):
        time = datetime.datetime.now()
        if self.created_at.day == time.day:
            if self.created_at.hour == time.hour:
                return str(time.min - self.created_at.min) + " mins ago"
            else:
                return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str() + str(self.created_at.day) + "/" +str(self.created_at.month) + "/" +str(self.created_at.year)
        return self.created_at

    #do this later
    def get_time(self):
        time = datetime.datetime.now()
        if self.created_at.hour == time.hour:
            return str(time.min - self.created_at.min) + " mins ago"
        else:
            if self.created_at.day == time.day:
                return str(time.hour - self.created_at.hour) + " hours ago"
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str() + str(self.created_at.day) + "/" +str(self.created_at.month) + "/" +str(self.created_at.year)
        return self.created_at

apps/communication/forms.py
from django import forms
from django.template.context_processors import request

from .models import Messages
from apps.product.models import Comments

from django import forms
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comments.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comments
        fields = ('made_by', 'name', 'email', 'made_on', 'parent', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-text-control', 'placeholder':'write a comment'}),
        }

    def save(self, *args, **kwargs):
        Comments.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)


class MessageForm(forms.ModelForm):
    content = forms.CharField(label='', max_length=255, help_text='Required', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Write your messages', 'id': 'login'
                                                                                       'edit-storename'}))
    class Meta:
        model= Messages
        fields=('content',)

apps/communication/views.py
import datetime
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.core import serializers

import random
from apps.cart.cart import Cart
from apps.product.forms import AddToCartForm, AddCategoryForm, ColorSearchForm
from apps.product.models import Category, Product, ProductType, ProductSpecificationValue, Comments
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.communication.forms import NewCommentForm


from apps.product.models import Product, Comments
from apps.vendor.models import Vendor, Subscriptions
from apps.account.models import UserBase
from .forms import MessageForm
from .models import Messages





@login_required
def messages_history(request, user_or_vendor_unique_id):
    for i in request.user.which_vendor.vendor_follower.all():
        print(i.follower.user_name)
    all_sender_list = []
    msg_sender_data = []
    unread_msg = Messages.objects.filter(reciever_id_unique=user_or_vendor_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=user_or_vendor_unique_id, is_seen=True).order_by('-created_at')
    try:
        user = UserBase.objects.get(unique_id=user_or_vendor_unique_id)
    except:
        user = Vendor.objects.get(unique_id=user_or_vendor_unique_id)

    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=user_or_vendor_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        print(i.sender_id_unique)
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                print('place--------1')
                print(sender.is_authenticated)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                online = sender.created_by.is_authenticated
                print('place--------2')
                print(online)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, msg_count, 'a_user'])

    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                print('place--------3')
                print(sender.is_authenticated)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])

            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                online = sender.created_by.is_authenticated
                print('place--------4')
                print(online)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, 0, 'a_user'])
    form = MessageForm()
    print(msg_sender_data)

    return render(request, 'communication/chat_platform.html', {"msg_sender_data": msg_sender_data, 'user':user, 'form': form})


@login_required
def get_message(request, user_unique_id, logged_in_user_unique_id):
    messages = Messages.objects.filter(sender_id_unique=user_unique_id, reciever_id_unique=logged_in_user_unique_id, is_seen=False)
    for status in messages:
        status.is_seen = True
        status.save()
    all_sender_list = []
    msg_sender_data = []
    unread_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=True).order_by('-created_at')
    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=logged_in_user_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, msg_count, 'a_user'])


    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])

            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, 0, 'a_user'])

    user_or_vendor_id = [user_unique_id, logged_in_user_unique_id]
    our_chat = Messages.objects.filter(sender_id_unique__in=user_or_vendor_id, reciever_id_unique__in=user_or_vendor_id).values(
        "sender_id_unique", 'content', 'created_at').order_by('-created_at')
    try:
        user_unique_id = UserBase.objects.get(unique_id=user_unique_id)
    except:
        user_unique_id = Vendor.objects.get(unique_id=user_unique_id)
    form = MessageForm()
    return render(request, 'communication/chat_platform2.html', {"our_chat":our_chat, "user_id":[user_unique_id, logged_in_user_unique_id],
                                                                "msg_sender_data": msg_sender_data, 'form': form})

@login_required
def send_message(request, user_unique_id, logged_in_user_unique_id):
    #messages = Messages.objects.filter(sender_id_unique=user_unique_id, reciever_id_unique=logged_in_user_unique_id, is_seen=False)
    print('user_or---------------')
    print(user_unique_id)
    print(logged_in_user_unique_id)
    print('user_or----------------')
    all_sender_list = []
    msg_sender_data = []

    if request.method == "POST":
        sent_message = request.POST.get('sent_message', '')
        Messages.objects.create(sender_id_unique=logged_in_user_unique_id,content=sent_message,
                                reciever_id_unique=user_unique_id)
    unread_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=True).order_by('-created_at')
    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=logged_in_user_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, msg_count, 'a_user'])


    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.store_name, sender.vendor_image.all(), i.content, i.get_date, 0, 'a_user'])

    user_or_vendor_id = [user_unique_id, logged_in_user_unique_id]
    our_chat = Messages.objects.filter(sender_id_unique__in=user_or_vendor_id, reciever_id_unique__in=user_or_vendor_id).values(
        "sender_id_unique", 'content', 'created_at').order_by('-created_at')
    try:
        user_unique_id = UserBase.objects.get(unique_id=user_unique_id)
    except:
        user_unique_id = Vendor.objects.get(unique_id=user_unique_id)
    form = MessageForm()
    return render(request, 'communication/chat_platform2.html', {"our_chat":our_chat, "user_id":[user_unique_id, logged_in_user_unique_id],
                                                                "msg_sender_data": msg_sender_data, 'form': form})



@login_required
def send_fleet_message(request):
    if request.POST.get('do_action') == 'post_it':
        unique_id_list = request.POST.getlist('unique_id_list[]')
        sent_fleet_msg = request.POST.get('sent_fleet_msg')
        for unique_id in unique_id_list:
            Messages.objects.create(sender_id_unique=request.user.which_vendor.unique_id,

apps/communication/templates/communication/chat_platform-1.html
{% extends 'core/base.html' %}

{% load static %}
{% block stylesheet %}{% static 'styles/communication/chat_platform.css' %}{% endblock %}

{% block title %}{% if request.user.is_authenticated %} {{ request.user.user_name }} | {% endif %}Chat{% endblock %}

{% block content %}
<section id="main-container">
  <div class="main-box">
      <div class="main-head">
      </div>
      <div class="box">
          <div class="inside-box">
              <div class="body-row">
                  <div class="firstbox">
                      {% if user.unique_id == request.user.unique_id %}
                      <div class="block1"><span>{{ request.user.user_name }}</span><span><i class="myBtn2" class="fa fa-pencil"></i></span></div>
                      {% elif user.unique_id == request.user.which_vendor.unique_id %}
                      <div class="block1"><span>{{ request.user.which_vendor.store_name }}</span><span><i class="myBtn2" class="fa fa-pencil"></i></span></div>
                      {% endif %}
                      <div class="block2"></div>
                  </div>
                  <div class="secondbox">
                      <div class="block1">
                        {% if msg_sender_data %}
                        {% for sender in msg_sender_data %}
                        <a class="inside" data-index="{{sender.0}}" {% if sender.6 == 'a_vendor' %} href="{% url 'message_:chat_platform2' sender.0 request.user.which_vendor.unique_id %}" {% else %} href="{% url 'message_:chat_platform2' sender.0 request.user.unique_id %}" {% endif %}>
                            <div class="inner">
                                {% if sender.6 == 'a_vendor' %}
                                <img src="{{ sender.2.url }}" alt="profile-image">
                                {% else %}
                                {% for sender in sender.2 %}
                                {% if sender.is_main %}
                                <img src="{{ sender.image_value.images.url }}" alt="profile-image">
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <span class="active"></span>
                            </div>
                            <div class="chat-lines">
                                <div>{{sender.1}}</div>
                                <input type="hidden" value="{{sender.3}}">
                                <span class="all msg">{{sender.3 | truncatechars:25}}</span>
                                <span class="all msg1">{{sender.3 | truncatechars:20}}</span>
                                <span class="all msg2">{{sender.3 | truncatechars:15}}</span>
                                <span class="all msg3">{{sender.3 | truncatechars:10}}</span>
                            </div>
                            <span class="time">.{{sender.4}}</span>
                            {% if sender.5 != 0 %}<span class="msg_amt" data-index="{{sender.0}}"> {{sender.5}}</span> {% endif %}
                        </a>
                        {% endfor %}
                         {% else %}
                          <p class="no-msg">no message</p>
                        {% endif %}
                      </div>
                      <div class="block2 block2-a">
                          <div class="inside inside-a">
                              <span><i class="fa fa-envelope-o" style="font-size:25px;"></i></span>
                              <span>Your Messages</span>
                              <span>Send private photos and messages to a friend or group.</span>
                              <button class="myBtn">Send Messages</button>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
        <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
          <div class="line1">
              <span class="close">&times;</span>
              <div>New Message</div>
              <div>Next</div>
          </div>
          <form method="post" action="">
              {% csrf_token %}
              <textarea rows="5" wrap="hard soft" autofocus="autofocus" placeholder="Write a message" name="sent_message"></textarea>
              <button class="msg-btn" type="submit"><i class="fa fa-caret-right"></i></button>
          </form>
          <div class="body">
              {% if request.user.is_authenticated %}
              {% for i in request.user.which_vendor.followers.all %}
              <div class="inside" data-index="{{ i.unique_id }}">
                  <div class="inner">
                    <img src="{{ i.user_image.url }}" alt="profile-image">
                    <span class="active"></span>
                    <div class="name">{{i.user_name}}</div>
                  </div>
                  <input class="search-input" data-index="{{ i.unique_id }}" type="checkbox">
              </div>
              {% endfor %}
              {% endif %}
          </div>
      </div>

    </div>

</section>
{% endblock %}

{% block scripts %}
    <script>
    $(document).ready(function(){
        $('.msg-btn').on(
            {click: function(e){
                e.preventDefault();
                var unique_id_list = []
                sent_fleet_msg = $('textarea').val()
                $('.search-input').each(function(index, values){
                    console.log(index, values)
                    if ($(this).is(":checked")){
                        unique_id=$(this).data('index');
                        unique_id_list.push(unique_id)
                    }
                })
                $.ajax({
                    type:"POST",
                    url:"{% url 'message_:send_fleet_message' %}",
                    data: {
                        unique_id_list: unique_id_list,
                        sent_fleet_msg: sent_fleet_msg,
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        do_action: 'post_it'
                    },
                    success: function(json){
                        console.log('completed with success');
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });
                console.log(unique_id_list)
                console.log(sent_fleet_msg)
            }}
        )


        var modal = document.getElementById("myModal");
        var btn = document.getElementsByClassName("myBtn")[0];

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks on the button, open the modal
        btn.onclick = function() {
          modal.style.display = "block";
        }
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }

        $('form').on( 'keyup', 'textarea', function (){
            $(this).height( 0 );
            $(this).height( this.scrollHeight );
        });
        $('form').find( 'textarea' ).keyup();



        $('.msg').css('display','block')

        function windowz(){
            if (window.matchMedia("(max-width:1050px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 20) {
                    $('.all').css('display','none')
                    $('.msg1').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:900px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 15) {
                    $('.all').css('display','none')
                    $('.msg2').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:768px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 10) {
                    $('.all').css('display','none')
                    $('.msg3').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:768px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 10) {
                    $('.all').css('display','none')
                    $('.msg2').css('display','block')
                }
            };
        }
        var y = window.matchMedia("(max-width:768px)")
        windowz()
        y.addListener(windowz)

        $('.secondbox > .block1 > .inside').on(
            {mousedown: function(){
                $('.secondbox > .block1').children().css('background-color','var(--normalwhite)')
                $(this).css('background-color','var(--lightgrey)')

                var unique_id = $(this).data('index')
                $('.msg_amt[data-index="'+ unique_id +'"]').remove();
            }}
        )
        $('.chatz').on(
            {click: function(e){
                e.preventDefault();
                $.ajax({
                    type:"POST",
                    data: {
                        ID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: 'get_msg'
                    },
                    success: function(json){
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )
    });
    </script>
{% endblock %}