apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import UserLoginForm, PassResetForm, PassResetConfirmForm

app_name="account_"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    #path ('', connection.new_user, name = 'new_user'),
    path('check-registration/', views.registration_check, name="registration_check"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('delete/', views.delete_account, name="delete_account"),
    path('delete_confirmation/', auth_views.TemplateView.as_view(
        template_name='account/user/delete_confirmation.html'), name="delete_confirmation"),

    #this here takes u to form where u enter email, then on click of button, to page saying u did it successfully
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='account/user/password_reset_form.html',
        success_url='password_reset_email_confirm',
        email_template_name='account/user/password_reset_email.html',
        form_class=PassResetForm),
        name="password_reset"),

    path('edit_login/', auth_views.PasswordResetView.as_view(
            template_name='account/user/password_reset_form.html',
            success_url='password_reset_email_confirm',
            email_template_name='account/user/password_reset_email.html',
            form_class=PassResetForm),
            name="edit_login"),

    #d page saying u did it successfully
    path('password_reset/password_reset_email_confirm/', auth_views.TemplateView.as_view(
        template_name='account/user/reset_status.html'), name="password_reset_done"),

    #this appears in ur email, on click this takes u to password_reset_complete
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/user/password_reset_confirm.html',
        success_url='/account/password_reset_complete/',
        form_class=PassResetConfirmForm),
        name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.TemplateView.as_view(
        template_name='account/user/reset_status.html'), name="password_reset_complete"),
    path('register/', views.account_registration, name="register"),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activation,  name="activate_"),
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name="logout"),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/set_default/", views.set_default, name="set_default"),
    #path("user_orders/", views.user_orders, name="user_orders"),
    path("", views.search_account, name="search_account"),
    path('dashboard_ajax/', views.dashboard_ajax, name="dashboard_ajax"),
    path("likes_and_wishlist/", views.likes_and_wishlist, name="likes_and_wishlist"),
    path("wishlist/wishlist_add_and_remove/<int:id>/", views.wishlist_add_and_remove, name="wishlist_add_and_remove"),
    path("wishlist/remove_from_wishlist/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("likes/remove_from_likes/", views.remove_from_likes, name="remove_from_likes"),
]

apps/checkout/urls.py
from django.urls import include, path
from django.conf.urls import url

from . import views

app_name = "checkout_"

urlpatterns = [
    path("delivery-choices", views.deliverychoices, name="delivery_choice"),
    path("cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("all", views.complete_payment, name="complete_payment2"),
    #url(r'^create_order/(?P<ref>\d*)$', views.complete_payment, name='complete_payment2')
    #path("payment_successful/", views.payment_successful, name="payment_successful"),
]

apps/core/urls.py
from django.urls import path
from . import views
from apps import communication

app_name="core_"
urlpatterns = [
    path('', views.frontpage, name="frontpage"),
    path('contact/', views.contact, name="contact"),
    path('search/<slug:category>/', views.category_search, name="category_search"),
    path("<slug:user_unique_id>/<slug:logged_in_user_unique_id>/error", communication.views.send_message, name="send_msg"),
]

apps/order/urls.py
from django.urls import path
from . import views
#from . import utilities

app_name="order_"
urlpatterns = [
    path('dashboard/<slug:user_name>/<slug:unique_id>/', views.user_orders, name="user_orders"),
    path('vendor/<slug:store_name>/<slug:unique_id>/', views.vendor_orders, name="vendor_orders"),
    #path("addresses/", views.view_address, name="addresses"),
    #path("add_address/", views.add_address, name="add_address"),
    #path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    #path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    #path("addresses/set_default/", views.set_default, name="set_default"),
]

mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('apps.payment.urls', namespace='payment_')),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.core.urls', namespace='core_')),
    path('', include('apps.product.urls', namespace='product_')),
    path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from decimal import Decimal

from apps.account.models import UserBase
from apps.vendor.models import Vendor



class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_METHODS = [
        ("In Store", "In Store"),
        ("Home Delivery", "Home Delivery"),
    ]
    DELIVERY_NAMES = [
        ("NONE", ""),
        ("Standard Delivery", "Standard Delivery"),
        ("Next Day Delivery", "Next Day Delivery"),
        ("Week Delivery", "Week Delivery"),
    ]
    PRICE_CHOICES = [
        ("Island", 150),
        ("Mainland", 200),
        ("Outliers", 250),
        ("NW", 1500),
        ("NE", 1500),
        ("NC", 1500),
        ("SW", 1000),
        ("SE", 1000),
        ("SS", 1000),
        """("NONE", Decimal(0)),
        ("IS", Decimal(15.00)),
        ("ML", Decimal(20.00)),
        ("OL", Decimal(25.00)),
        ("NW", Decimal(150.00)),
        ("NE", Decimal(150.00)),
        ("NC", Decimal(150.00)),
        ("SW", Decimal(100.00)),
        ("SE", Decimal(100.00)),
        ("SS", Decimal(100.00)),"""
    ]
    TIME_FRAME_CHOICES = [
        ("24hours", "24hours"),
        ("48hours", "48hours"),
        ("72hours", "72hours"),
    ]
    REGION_CHOICES = [
        ("None", ""),
        ("Island", "Island"),
        ("Mainland", "Mainland"),
        ("Outliers", "Outliers"),
        ("NW", "North West"),
        ("NE", "North East"),
        ("NC", "North Central"),
        ("SW", "South West"),
        ("SE", "South East"),
        ("SS", "South South"),
    ]
    WINDOW_CHOICES = [
        ("None", ""),
        ("5.00am", "5.00am to 10.00pm"),
        ("10.00am", "10.00am to 3.00pm"),
        ("3.00pm", "3.00pm to 7.00pm"),
        ("7.00pm", "7.00pm to 12.00pm"),
    ]
    delivery_name = models.CharField(choices=DELIVERY_NAMES,verbose_name=_("delivery_name"),help_text=_("Required"),max_length=255,)
    delivery_region = models.CharField(choices=REGION_CHOICES, null=True,verbose_name=_("delivery_location"),help_text=_("Required"),max_length=255,)
    delivery_price = models.IntegerField(verbose_name=_("delivery price"))
    #delivery_price = models.DecimalField(verbose_name=_("delivery price"),help_text=_("Maximum 999.99"),
    #    error_messages={
    #        "name": {"max_length": _("The price must be between 0 and 999.99."),},
    #    },
    #    max_digits=5,
    #    decimal_places=2,
    #)"""
    delivery_method = models.CharField(choices=DELIVERY_METHODS,verbose_name=_("delivery_method"),help_text=_("Required"),max_length=255,)
    delivery_timeframe = models.CharField(choices=TIME_FRAME_CHOICES,verbose_name=_("delivery timeframe"),help_text=_("Required"),max_length=255,)
    delivery_window = models.CharField(choices=WINDOW_CHOICES,verbose_name=_("delivery window"),help_text=_("Required"),max_length=255,)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    PAYMENT_SELECTIONS = [
        ("Paystack", "Paystack"),
        ("Paypal", "Paypal"),
        ("Stripe", "Stripe"),
    ]
    name = models.CharField(choices=PAYMENT_SELECTIONS, verbose_name=_("name"), help_text=_("Required"), max_length=255,)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

apps/checkout/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

from apps.order.models import OrderReciept, OrderedItemDetail, Address, Checkout
from apps.cart.cart import Cart

from .models import DeliveryOptions, PaymentSelections


@login_required
def deliverychoices(request):
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    return render(request, "checkout/delivery_choices.html", {"deliveryoptions": deliveryoptions})


@login_required
def cart_update_delivery(request):
    cart = Cart(request)
    if request.POST.get("action") == "post":
        delivery_option = int(request.POST.get("deliveryoption"))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = cart.cart_update_delivery(delivery_type.delivery_price)

        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {"delivery_id": delivery_type.id}
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True
        response = JsonResponse({"total": updated_total_price, "delivery_price": delivery_type.delivery_price})
        return response


@login_required
def delivery_address(request):
    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = Address.objects.filter(customer=request.user).order_by("-default")

    if addresses:
        if "address" not in request.session:
            session["address"] = {"address_id": str(addresses[0].pk)}
        else:
            session["address"]["address_id"] = str(addresses[0].pk)
            session.modified = True
        return render(request, "checkout/delivery_address.html", {"addresses": addresses})


@login_required
def payment_selection(request):
    # print(request.COOKIES)
    session = request.session
    if "address" not in session:
        messages.success(request, "Please select address option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        id = session["address"]['address_id']
        address = Address.objects.get(id=id)

    return render(request, "checkout/payment_selection.html", {'address': address})


@login_required
def complete_payment(request):
    # def complete_payment(request: HttpRequest, response: str) -> HttpResponse:
    cart = Cart(request)
    session = request.session
    if request.POST.get('action') == 'post':
        ref = request.POST.get('ref')
        amount = request.POST.get('amount')
        address_id = session["address"]["address_id"]
        delivery_id = session["purchase"]["delivery_id"]
        address = request.user.user_address.get(id=address_id)
        payment_selection = PaymentSelections.objects.get(name='Paystack')
        delivery_instructions = DeliveryOptions.objects.get(id=delivery_id)
        order = OrderReciept.objects.create(
            user_id=request.user.id, delivery_address=address, delivery_instructions=delivery_instructions,
            total_paid=amount, payment_option=payment_selection
        )
        for item in cart:
            OrderedItemDetail.objects.create(order=order, product=item['product'], vendor=item['product'].vendor,
                                             amount=item['total_price'], quantity=item['quantity'])
        verified = order.verify_payment(amount, ref)
        print('verified')
        print(verified)
        print('verified')
        if verified:
            order.verified = True
            order.save()
            Checkout.objects.create(order=order, ref=ref)

            messages.success(request, "Payment verification was sucessfull")
        else:
            messages.success(request, "Your payment verification failed")
        return redirect('.')


from paypalcheckoutsdk.orders import OrdersGetRequest

from .paypal import PayPalClient


@login_required
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body["orderID"]
    user_id = request.user.id

    # this sends our order data to paypal API through d API function OrdersGetRequest
    requestorder = OrdersGetRequest(data)
    # this is paypal response to us containing all details about the order
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value

    cart = Cart(request)
    order = OrderReciept.objects.create(
        user_id=user_id,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        address1=response.result.purchase_units[0].shipping.address.address_line_1,
        address2=response.result.purchase_units[0].shipping.address.admin_area_2,
        postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        country_code=response.result.purchase_units[0].shipping.address.country_code,
        total_paid=response.result.purchase_units[0].amount.value,
        order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order_id = order.pk

    for item in cart:
        OrderedItemDetail.objects.create(order=order, product=item["product"], price=item["product"].price,
                                         quantity=item["qty"])

    return JsonResponse("Payment completed!", safe=False)


"""
@login_required
def payment_successful(request):
    chats = Cart(request)
    chats.clear()
    return render(request, "checkout/payment_successful.html", {})"""

apps/checkout/templates/checkout/delivery_address.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>


<div class="container">
  <div class="row g-3">
    {% if addresses|length == 0 %}
    <div class="col-12">There are no delivery addresses, <a href="{% url 'account_:add_address' %}">add address</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">

      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"class="fw-bold h5">{{cart.get_subtotal_cost}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price" class="fw-bold h5">{{cart.get_delivery_cost}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"class="fw-bold h5">{{cart.get_total_cost}}</span></div>
      </div>
      <a role="button" href="{% url 'checkout_:payment_selection' %}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
      </div>

      <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
        <h1 class="h5 pt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
              </div>s
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  <a href="{% url 'account_:edit_address' address.id %}" class="edit">Edit</a>
                  {% if not address.default %}
                  | <a href="" data-index="{{address.id}}" class="default">Default</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock %}


{% block scripts %}
<script>
  $('.default').on('click', function(e) {
    e.preventDefault();
    var address_id=$(this).data('index');
    $.ajax({
      type: "POST",
      url: '{% url 'account_:set_default' %}',
      data: {
        address_id: address_id,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
      },
      error: function (xhr, errmsg, err) {},
    });

  });
</script>


{% endblock %}

apps/checkout/templates/checkout/delivery_choices.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Select your delivery options</p>
  </div>
  <hr />
</div>


<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
  {% for message in messages  %}
    {{message|safe}}
  {% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    {% if deliveryoptions|length == 0 %}
    <div class="col-12">There are no delivery options <a href="{% url "core_:frontpage" %}">Shop</a></div>
    {% else %}
    <div class="">
      <div class="">
        <div class="">Sub Total:</div>
        <div class=""><span class="">£</span><span id="sub_total"
            class="">{{cart.get_subtotal_cost}}</span></div>
      </div>
      <div class="">
        <div class="">Delivery Cost:</div>
        <div class=""><span class="5">£</span><span id="delivery_price"
            class="">{{cart.get_delivery_price}}</span></div>
      </div>
      <div class="">
        <div class="">Total:</div>
        <div class=""><span class="">£</span><span id="total"
            class="">{{cart.get_total_cost}}</span></div>
      </div>
      <a role="button" href="{% url "checkout_:delivery_address" %}" class=""
        type="button">Pay Securely</a>
    </div>
    <div class="">
      {% for option in deliveryoptions %}
      {% if option.is_active %}
      <div class="card" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="">
            <i class="fa fa-car"></i>
          </div>
          <div class="">
            <div class="card-body">
              <p class="card-text">{{option.delivery_name}}</p>
              <p class="card-text">Your order should be delivered within {{option.delivery_timeframe}} day</p>
              <p class="card-text"><span>delivery region</span> <span>{{option.delivery_region}}</span></p>
              <p class="card-text"><span>delivery method</span> <span>{{option.delivery_method}}</span></p>
              <p class="card-text"><span>delivery window</span> <span>{{option.delivery_window}}</span></p>

            </div>
          </div>
          <div class="">
            <input class="" type="radio" {% if request.user.order_user.payment_option == option %} checked {% endif %} name="deliveryOption" id="{{option.id}}"
              value="{{option.id}}">
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

<script>
  $('input[type=radio][name=deliveryOption]').on('change', function(e) {
    e.preventDefault();
    console.log($(this).val())
    $.ajax({
      type: "POST",
      url: '{% url "checkout_:cart_update_delivery" %}',
      data: {
        deliveryoption: $(this).val(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("total").innerHTML = json.total;
        document.getElementById("delivery_price").innerHTML = json.delivery_price;
      },
      error: function (xhr, errmsg, err) {},
    });
    
  });
</script>


{% endblock %}

apps/checkout/templates/checkout/payment_selection.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Payment Selection{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery option</p>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{cart.get_subtotal_cost}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{cart.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{cart.get_total_cost}}</span></div>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
      <div id="paypal-button-container">
        <span>Make Payment</span>
        <form id="paymentForm">
          {% csrf_token %}
          <button onclick="payWithPaystack()">Pay now</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script>

  var email = "{{address.email}}"
  var key = "{{key}}"
  var amt = "{{cart.get_total_cost}}"
  console.log(email)
  console.log(amt)
  console.log(key)

  var paymentForm = document.getElementById('paymentForm');
  paymentForm.addEventListener('submit', payWithPaystack, false);
  function payWithPaystack() {
    console.log('iiiiittttttssssss commmmminnnnnnnng')
    var handler = PaystackPop.setup({
      key: 'pk_test_1bd3d130cbb6f84a90e8cdb0e13a82a659ebbedc', // Replace with your public key
      email: email,
      //withCredentials: true,
      //crossDomain: true,
      amount: amt * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
      currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // Replace with a reference you generated
      callback: function(response) {
        //let message = 'Payment complete! Reference: ' + response.reference;
        //alert(message);
        window.location.href = "{% url 'checkout_:complete_payment' %}"
      },
      onClose: function() {
        alert('Transaction was not completed, window closed.');
      },
    });
    handler.openIframe();
  }
/*
`http-server . --cors`
  $.ajax('http://authorization.proj.io', {
    type: "GET",
    contentType: "application/json; charset=utf-8",
    success: function(data, status, xhr) {
      // do something;
    },
    error: function(jqxhr, textStatus, errorThrown) {
    console.log("cannot get orgs");
    },
    xhrFields: {
    withCredentials: true
    },
    crossDomain: true
}); */
</script>
<!--
<script
  src="https://www.paypal.com/sdk/js?client-id=ARu-_pPT7to2ublMfXlzrhpsL9Xlye694JATZR3RBYPU3bQbmhqdTpkDvmq9KZleBmP0g5qGRYafWfRq&currency=USD"
  data-sdk-integration-source="button-factory">
</script>
    <script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');



  function initPayPalButton() {
    paypal.Buttons({
      style: {
        shape: 'rect',
        color: 'gold',
        layout: 'vertical',
        label: 'paypal',

      },
    createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [{
            "amount": {
              "currency_code": "USD",
              "value": '{{chats.get_total_cost}}'
            }
          }]
        });
      },
    onApprove: function (data) {
        var url = "{% url 'checkout_:payment_complete' %}"
        return fetch(url, {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'X-CSRFToken': csrftoken,
          },
          body: JSON.stringify({
            orderID: data.orderID
          })
        }).then(function () {
          location.href = '';
        })
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();

    </script> -->

{% endblock %}

apps/checkout/templates/checkout/payment_successful.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Payment Successful</h1>
  </div>
  <div class="col-12">
    <p>Order Summary</p>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'account:user_orders'%}">orders</a></p>
  </div>
</div>


{% endblock %}